name: Compile blueprint

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Cancel previous runs if a new commit is pushed to the same branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Cleanup to free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout project
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Build project
        uses: leanprover/lean-action@v1
        with:
          build: true
          test: false
          lint: false

      - name: Check declarations mentioned in the blueprint exist in Lean code
        run: lake exe checkdecls blueprint/lean_decls

      - name: Compile blueprint and documentation
        uses: leanprover-community/docgen-action@7b5b9a1822650bd45aaeb4182d94bceba2030f89 # 2026-04-14
        with:
          blueprint: true
          homepage: docs
