name: Update Dependencies

on:
  schedule:
    - cron: "0 8 */7 * *" # Every 7 days at 08:00 UTC
  workflow_dispatch:      # Allows the workflow to be triggered manually via the GitHub interface

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      is-update-available: ${{ steps.check-for-updates.outputs.is-update-available }}
      new-tags: ${{ steps.check-for-updates.outputs.new-tags }}
    steps:
      - name: Run the action
        id: check-for-updates
        uses: leanprover-community/mathlib-update-action@main
        with:
          intermediate_releases: all
          legacy_update: true

  do-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: check-for-updates
    if: ${{ needs.check-for-updates.outputs.is-update-available == 'true' }}
    strategy:
      max-parallel: 1
      matrix:
        tag: ${{ fromJSON(needs.check-for-updates.outputs.new-tags) }}
    steps:
      - name: Run the action
        id: update-the-repo
        uses: leanprover-community/mathlib-update-action/do-update@main
        with:
          tag: ${{ matrix.tag }}
          legacy_update: true
